/**
 * Auto-generated by scripts/generate-story-media.mjs
 * Maps each story slug to media files in src/assets/Combined/
 */

const combinedModules = import.meta.glob('./assets/Combined/*', {
  eager: true,
  query: '?url',
  import: 'default',
})

const urlByFilename = Object.fromEntries(
  Object.entries(combinedModules).map(([modulePath, url]) => {
    const filename = modulePath.split('/').pop()
    return [filename, url]
  }),
)

export const storyAssetManifest = {
  "abdirahman-nour-youssef": {
    "heroDesktop": "Maandhis-111111111.jpg",
    "heroMobile": "Photo-Maandhis.jpg",
    "groupImage": "Mandhis3333333333333333333.jpg",
  },
  "ali-bendahbia": {
    "heroDesktop": "Ataafoundation_taza108.jpg",
    "heroMobile": "Ataafoundation_taza108.jpg",
    "statsImage": "ATAA_Taza-66.jpg",
    "portraitImage": "Ataa-Rawae-1.png",
    "groupImage": "ATAA-48.jpg",
  },
  "ola-alaghbaary": {
    "heroDesktop": "1fe89317-3f1e-49cf-9ce8-52f152e5a857.jpeg",
    "heroMobile": "1fe89317-3f1e-49cf-9ce8-52f152e5a857.jpeg",
    "statsImage": "WhatsApp-Image-2025-10-25-at-4.51.58-PM.jpeg",
    "portraitImage": "WhatsApp-Image-2025-10-25-at-4.53.21-PM.jpeg",
    "groupImage": "WhatsApp-Image-2025-10-25-at-5.00.47-PM.jpeg",
  },
  "seada-hassan-aqar": {
    "heroDesktop": "WhatsApp-Image-2025-12-03-at-15.40.18-1.jpeg",
    "heroMobile": "WhatsApp-Image-2025-12-03-at-15.40.18-1.jpeg",
    "statsImage": "WhatsApp-Image-2025-12-03-at-15.37.40-1.jpeg",
    "portraitImage": "WhatsApp-Image-2025-12-03-at-15.37.39.jpeg",
    "groupImage": "WhatsApp-Image-2025-12-03-at-15.40.20-1.jpeg",
  },
  "gabby-fraidy": {
    "heroDesktop": "Gabby.jpg",
    "heroMobile": "Gabby.jpg",
    "statsImage": "Gender-based-violence-awareness-session-implemented-for-sudanese-Women-2018-Beirut.jpg",
    "portraitImage": "UNDP-Partner-Youth-Leadership-program-2023.jpg",
    "groupImage": "playing-with-children-during-war-2025-South-Jooun.jpg",
    // "video": "Clinincal-management-of-rape-training-implemented-by-me-for-doctors-in-one-of-the-governemantal-hospitals-in-Lebanon-Akkar-2025.mp4"
  },
  "moukhtar-itani": {
    "heroDesktop": "Sprout-2022-Pitching-the-idea-of-how-non-natural-pillow-can-affect-achieving-sustainable-development-goals,-and-solution-with-green-deep-sleep-fnf.jpeg",
    "heroMobile": "Sprout-2022-Pitching-the-idea-of-how-non-natural-pillow-can-affect-achieving-sustainable-development-goals,-and-solution-with-green-deep-sleep-fnf.jpeg",
    "statsImage": "UNDP-YLP-10-Youth-forum,-2024-,-Introducing-youth-to-ecommerce-and-how-to-create-an-ecommerce-website-technical-workshop-at-Lebanese-American-University-Byblos-as-part-of-UNDP-YLP-Advisory-board-,-Q-and-A.jpeg",
    "portraitImage": "Mokhtar.jpeg",
    "groupImage": "Winning-3rd-place-at-sprout,-after-pitching-the-effect-of-pillows-on-nature-and-the-consumption-of-co2-and-the-solutions-Beirut-2022.jpeg",
  },
  "zahia-tahir-sagr": {
    "heroDesktop": "IMG-20251021-WA0035.jpg",
    "heroMobile": "IMG-20251021-WA0035.jpg",
    "statsImage": "IMG-20251007-WA0047.jpg",
    "portraitImage": "IMG_20250309_164256_resized_20251101_092907381.jpg",
    "groupImage": "",
  },
  "abdalla-babiker": {
    "heroDesktop": "FB_IMG_1759948093560.jpg",
    "heroMobile": "FB_IMG_1759948093560.jpg",
    "statsImage": "FB_IMG_1759948127204.jpg",
    "groupImage": "FB_IMG_1759948074706.jpg"
  },
  "raghda-breika": {
    "heroDesktop": "WhatsApp-Image-2025-12-01-at-11.26.25-2.jpeg",
    "heroMobile": "WhatsApp-Image-2025-12-01-at-11.26.25-3.jpeg",
    "statsImage": "WhatsApp-Image-2025-12-01-at-11.26.27-2.jpeg",
    "portraitImage": "WhatsApp-Image-2025-12-01-at-11.02.09-2.jpeg",
    "groupImage": "WhatsApp-Image-2025-12-01-at-11.26.25.jpeg",
  },
  "ahmad-assaf": {
    "heroDesktop": "IMG_4090.jpeg",
    "heroMobile": "IMG_4090.jpeg",
    "statsImage": "IMG_4044.jpeg",
    "portraitImage": "IMG_4042.jpeg",
    "groupImage": "IMG_4089.jpeg",
  },
  "nourshan": {
    "heroDesktop": "96969afc-f27d-45f6-8209-b50bfa0b59d1.jpeg",
    "heroMobile": "96969afc-f27d-45f6-8209-b50bfa0b59d1.jpeg",
    "statsImage": "IMG_6791.jpeg",
    "portraitImage": "5e11ac9a-98d3-43d5-a978-69a30c5ced34.jpeg",
    "groupImage": "IMG_4899.jpeg",
  },
  "muad-al-ghandouri": {
    "heroDesktop": "IMG_6794.jpeg",
    "heroMobile": "IMG_6794.jpeg",
    "statsImage": "IMG_7643.jpg",
    "groupImage": "IMG_7640.jpg",
  },
  "khairyyeh-bobaky": {
    "heroDesktop": "IMG_9878.jpeg",
    "heroMobile": "IMG_9878.jpeg",
    "statsImage": "IMG_4478.jpeg",
    "portraitImage": "IMG_9878.jpeg",
  },
  "omar-bozou": {
    "heroDesktop": "Damascus-2-2023-Voulanteers-gethering-AID-for-earthquake-effected-cities-4.jpg",
    "heroMobile": "Damascus-2-2023-Voulanteers-gethering-AID-for-earthquake-effected-cities-4.jpg",
    "statsImage": "Damascus-2-2023-Voulanteers-gethering-AID-for-earthquake-effected-cities-4.jpg",
    "portraitImage": "Damascus-9-2020-Akemha-Voulanteers-cleansing-school.jpg",
    "groupImage": "Damascus-2-2023-Voulanteers-gethering-AID-for-earthquake-effected-cities-2.jpg",
  }
}

export function getStoryAssets(slug) {
  const files = storyAssetManifest[slug]
  if (!files) return {}
  const resolved = {}
  for (const [key, filename] of Object.entries(files)) {
    const url = urlByFilename[filename]
    if (url) resolved[key] = url
  }
  return resolved
}
